/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Gabriel Pilan
 */
public class GUI_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public GUI_Menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadastrarMaterial = new javax.swing.JMenuItem();
        jMenuItemCadastrarCotacoes = new javax.swing.JMenuItem();
        jMenuItemCriarPedidoCompra = new javax.swing.JMenuItem();
        jMenuOperacoes = new javax.swing.JMenu();
        jMenuItemRequisicaoCompra = new javax.swing.JMenuItem();
        jMenuItemAssociarMaterialFornecedor = new javax.swing.JMenuItem();
        jMenuItemSelecionarCotacaoVencedora = new javax.swing.JMenuItem();
        jMenuItemDecisaoPedidoCompra = new javax.swing.JMenuItem();
        jMenuItemFinalizarCompra = new javax.swing.JMenuItem();
        jMenuItemAvaliarFornecedor = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConsultarRequisicao = new javax.swing.JMenuItem();
        jMenuItemConsultarMaterial = new javax.swing.JMenuItem();
        jMenuItemConsultarFornecedor = new javax.swing.JMenuItem();
        jMenuItemConsultarFornecedorMateriais = new javax.swing.JMenuItem();
        jMenuItemConsultarCotacao = new javax.swing.JMenuItem();
        jMenuItemConsultarCotacaoVencedora = new javax.swing.JMenuItem();
        jMenuItemConsultarPedidoCompra = new javax.swing.JMenuItem();
        jMenuItemConsultarRanking = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel1.setText("SISTEMA DE COMPRAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel2.setText("Versao: 0.1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Hora");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Nome do Funcionário");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Data");

        txtNomeFuncionario.setEditable(false);
        txtNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNomeFuncionario.setEnabled(false);

        txtData.setEditable(false);
        txtData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtData.setEnabled(false);

        txtHora.setEditable(false);
        txtHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtHora.setEnabled(false);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuLogin.setText("Login    ");
        jMenuLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuItemLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemLogin);

        jMenuBar1.add(jMenuLogin);

        jMenuCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuCadastro.setText("Gerenciar   ");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuItemCadastroUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemCadastroUsuario.setText("Gerenciar Usuário");
        jMenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroUsuario);

        jMenuItemCadastroFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemCadastroFornecedor.setText("Gerenciar Fornecedor");
        jMenuItemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroFornecedor);

        jMenuItemCadastrarMaterial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemCadastrarMaterial.setText("Gerenciar Material");
        jMenuItemCadastrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarMaterialActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastrarMaterial);

        jMenuItemCadastrarCotacoes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemCadastrarCotacoes.setText("Gerenciar Cotações de uma Requisição");
        jMenuItemCadastrarCotacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarCotacoesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastrarCotacoes);

        jMenuItemCriarPedidoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemCriarPedidoCompra.setText("Gerenciar Pedido de Compra");
        jMenuItemCriarPedidoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarPedidoCompraActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCriarPedidoCompra);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuOperacoes.setText("Operações   ");
        jMenuOperacoes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuItemRequisicaoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemRequisicaoCompra.setText("Requisição de Compra");
        jMenuItemRequisicaoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRequisicaoCompraActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemRequisicaoCompra);

        jMenuItemAssociarMaterialFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAssociarMaterialFornecedor.setText("Associar Material Fornecedor");
        jMenuItemAssociarMaterialFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAssociarMaterialFornecedorActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemAssociarMaterialFornecedor);

        jMenuItemSelecionarCotacaoVencedora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemSelecionarCotacaoVencedora.setText("Selecionar Cotação Vencedora");
        jMenuItemSelecionarCotacaoVencedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelecionarCotacaoVencedoraActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemSelecionarCotacaoVencedora);

        jMenuItemDecisaoPedidoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemDecisaoPedidoCompra.setText("Aprovar/Rejeitar Pedido de Compra");
        jMenuItemDecisaoPedidoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDecisaoPedidoCompraActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemDecisaoPedidoCompra);

        jMenuItemFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemFinalizarCompra.setText("Finalizar Compra");
        jMenuItemFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarCompraActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemFinalizarCompra);

        jMenuItemAvaliarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAvaliarFornecedor.setText("Avaliar Fornecedor");
        jMenuItemAvaliarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAvaliarFornecedorActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemAvaliarFornecedor);

        jMenuBar1.add(jMenuOperacoes);

        jMenuConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuConsultar.setText("Consultas   ");
        jMenuConsultar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuItemConsultarRequisicao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarRequisicao.setText("Consultar Requisição de Compra");
        jMenuItemConsultarRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarRequisicaoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarRequisicao);

        jMenuItemConsultarMaterial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarMaterial.setText("Consultar Material");
        jMenuItemConsultarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarMaterialActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarMaterial);

        jMenuItemConsultarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarFornecedor.setText("Consultar Fornecedor");
        jMenuItemConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarFornecedorActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarFornecedor);

        jMenuItemConsultarFornecedorMateriais.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarFornecedorMateriais.setText("Consultar Fornecedor de Materiais");
        jMenuItemConsultarFornecedorMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarFornecedorMateriaisActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarFornecedorMateriais);

        jMenuItemConsultarCotacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarCotacao.setText("Consultar Cotação");
        jMenuItemConsultarCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCotacaoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarCotacao);

        jMenuItemConsultarCotacaoVencedora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarCotacaoVencedora.setText("Consultar Cotação Vencedora");
        jMenuItemConsultarCotacaoVencedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCotacaoVencedoraActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarCotacaoVencedora);

        jMenuItemConsultarPedidoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarPedidoCompra.setText("Consultar Pedido de Compra");
        jMenuItemConsultarPedidoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarPedidoCompraActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarPedidoCompra);

        jMenuItemConsultarRanking.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemConsultarRanking.setText("Consultar Ranking");
        jMenuItemConsultarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarRankingActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarRanking);

        jMenuBar1.add(jMenuConsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(681, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuarioActionPerformed
        new GUI_GerenciarUsuario().setVisible(true); 
    }//GEN-LAST:event_jMenuItemCadastroUsuarioActionPerformed

    private void jMenuItemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroFornecedorActionPerformed
        new GUI_GerenciarFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroFornecedorActionPerformed

    private void jMenuItemAvaliarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAvaliarFornecedorActionPerformed
        new GUI_AvaliarFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAvaliarFornecedorActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        new GUI_Login().setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemRequisicaoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRequisicaoCompraActionPerformed
        new GUI_RequisicaoCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemRequisicaoCompraActionPerformed

    private void jMenuItemAssociarMaterialFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAssociarMaterialFornecedorActionPerformed
        new GUI_AssociarMaterialFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAssociarMaterialFornecedorActionPerformed

    private void jMenuItemConsultarFornecedorMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarFornecedorMateriaisActionPerformed
        new GUI_ConsultarFornecedorMaterial().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarFornecedorMateriaisActionPerformed

    private void jMenuItemConsultarRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarRequisicaoActionPerformed
        new GUI_ConsultarRequisicao().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarRequisicaoActionPerformed

    private void jMenuItemCadastrarCotacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarCotacoesActionPerformed
        new GUI_GerenciarCotacoesDeUmaRequisicao().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarCotacoesActionPerformed

    private void jMenuItemSelecionarCotacaoVencedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelecionarCotacaoVencedoraActionPerformed
        new GUI_CotacaoVencedora().setVisible(true); 
    }//GEN-LAST:event_jMenuItemSelecionarCotacaoVencedoraActionPerformed

    private void jMenuItemConsultarCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCotacaoActionPerformed
        new GUI_ConsultarCotacao().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarCotacaoActionPerformed

    private void jMenuItemConsultarPedidoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarPedidoCompraActionPerformed
        new GUI_ConsultarPedidoCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarPedidoCompraActionPerformed

    private void jMenuItemConsultarCotacaoVencedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCotacaoVencedoraActionPerformed
        new GUI_ConsultarCotacaoVencedora().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarCotacaoVencedoraActionPerformed

    private void jMenuItemCriarPedidoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarPedidoCompraActionPerformed
        new GUI_GerenciarPedidoCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemCriarPedidoCompraActionPerformed

    private void jMenuItemCadastrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarMaterialActionPerformed
        new GUI_GerenciarMaterial().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarMaterialActionPerformed

    private void jMenuItemConsultarRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarRankingActionPerformed
        new GUI_ConsultarRankingFornecedores().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarRankingActionPerformed

    private void jMenuItemDecisaoPedidoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDecisaoPedidoCompraActionPerformed
        new GUI_DecisaoPedidoCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemDecisaoPedidoCompraActionPerformed

    private void jMenuItemFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarCompraActionPerformed
        new GUI_FinalizarCompra().setVisible(true);
    }//GEN-LAST:event_jMenuItemFinalizarCompraActionPerformed

    private void jMenuItemConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarFornecedorActionPerformed
       new GUI_PesquisarFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarFornecedorActionPerformed

    private void jMenuItemConsultarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarMaterialActionPerformed
        new GUI_PesquisarMaterial().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItemAssociarMaterialFornecedor;
    private javax.swing.JMenuItem jMenuItemAvaliarFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastrarCotacoes;
    private javax.swing.JMenuItem jMenuItemCadastrarMaterial;
    private javax.swing.JMenuItem jMenuItemCadastroFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastroUsuario;
    private javax.swing.JMenuItem jMenuItemConsultarCotacao;
    private javax.swing.JMenuItem jMenuItemConsultarCotacaoVencedora;
    private javax.swing.JMenuItem jMenuItemConsultarFornecedor;
    private javax.swing.JMenuItem jMenuItemConsultarFornecedorMateriais;
    private javax.swing.JMenuItem jMenuItemConsultarMaterial;
    private javax.swing.JMenuItem jMenuItemConsultarPedidoCompra;
    private javax.swing.JMenuItem jMenuItemConsultarRanking;
    private javax.swing.JMenuItem jMenuItemConsultarRequisicao;
    private javax.swing.JMenuItem jMenuItemCriarPedidoCompra;
    private javax.swing.JMenuItem jMenuItemDecisaoPedidoCompra;
    private javax.swing.JMenuItem jMenuItemFinalizarCompra;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemRequisicaoCompra;
    private javax.swing.JMenuItem jMenuItemSelecionarCotacaoVencedora;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
