/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabriel Pilan
 */
public class GUI_ConsultarRequisicao extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ConsultarRequisicao
     */
    public GUI_ConsultarRequisicao() {
        initComponents();
        jTableRequisicao.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequisicao = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdRequisicao = new javax.swing.JTextField();
        btnBuscarRequisicao = new javax.swing.JButton();
        chkFiltrarRequisicoesAberto = new javax.swing.JCheckBox();
        btnFazerCotacao = new javax.swing.JButton();
        btnCopiarIDRequisicao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCotacao = new javax.swing.JTextField();
        btnBuscarCotacao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPedidoDeCompra = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        rbPesquisarRequisicaoCompra = new javax.swing.JRadioButton();
        rbPesquisarPedidoCompra = new javax.swing.JRadioButton();
        rbPesquisarCotacao = new javax.swing.JRadioButton();
        rbPesquisarTodas = new javax.swing.JRadioButton();
        rbPesquisarSetor = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBuscarSetor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Requisicao");
        setAlwaysOnTop(true);

        jLabel1.setText("Tabela de Requsições");

        jTableRequisicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Requerente", "Setor do Requerente", "Id Requisição", "Status", "Data da Requisição", "Id da Cotação Relacionada", "Id do Pedido de Compra"
            }
        ));
        jScrollPane1.setViewportView(jTableRequisicao);

        jLabel2.setText("Id Requisição");

        txtIdRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRequisicaoActionPerformed(evt);
            }
        });

        btnBuscarRequisicao.setText("Buscar");

        chkFiltrarRequisicoesAberto.setText("Filtrar por Requisições em Aberto");

        btnFazerCotacao.setText("Fazer Cotação(oes) da Requisição Selecionada");

        btnCopiarIDRequisicao.setText("Copiar Id da Requisição Selecionada");

        jLabel3.setText("Id da Cotação Relacionada");

        btnBuscarCotacao.setText("Buscar");

        jLabel4.setText("Id do Pedido de Compra");

        btnBuscar.setText("Buscar");

        buttonGroup1.add(rbPesquisarRequisicaoCompra);
        rbPesquisarRequisicaoCompra.setText("Pesquisar por ID da Requisição de Compra");

        buttonGroup1.add(rbPesquisarPedidoCompra);
        rbPesquisarPedidoCompra.setText("Pesquisar por ID do Pedido de Compra");

        buttonGroup1.add(rbPesquisarCotacao);
        rbPesquisarCotacao.setText("Pesquisar por ID da Cotação Relacionada");

        buttonGroup1.add(rbPesquisarTodas);
        rbPesquisarTodas.setSelected(true);
        rbPesquisarTodas.setText("Pesquisar todas as Requisições de Compra");

        buttonGroup1.add(rbPesquisarSetor);
        rbPesquisarSetor.setText("Pesquisar pelo Setor que Requeriu a Compra");

        jLabel5.setText("Nome do Setor");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarSetor.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPesquisarRequisicaoCompra)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFazerCotacao)
                                .addGap(18, 18, 18)
                                .addComponent(btnCopiarIDRequisicao))
                            .addComponent(chkFiltrarRequisicoesAberto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPesquisarPedidoCompra)
                                    .addComponent(rbPesquisarCotacao)
                                    .addComponent(rbPesquisarTodas)
                                    .addComponent(rbPesquisarSetor))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPedidoDeCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdRequisicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscar)
                                            .addComponent(btnBuscarRequisicao)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCotacao, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscarCotacao)
                                            .addComponent(btnBuscarSetor))))))
                        .addGap(0, 367, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rbPesquisarTodas)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRequisicao)
                    .addComponent(rbPesquisarRequisicaoCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPedidoDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(rbPesquisarPedidoCompra))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCotacao)
                    .addComponent(rbPesquisarCotacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPesquisarSetor)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSetor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(chkFiltrarRequisicoesAberto)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFazerCotacao)
                    .addComponent(btnCopiarIDRequisicao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRequisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRequisicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ConsultarRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ConsultarRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ConsultarRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ConsultarRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ConsultarRequisicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCotacao;
    private javax.swing.JButton btnBuscarRequisicao;
    private javax.swing.JButton btnBuscarSetor;
    private javax.swing.JButton btnCopiarIDRequisicao;
    private javax.swing.JButton btnFazerCotacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkFiltrarRequisicoesAberto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRequisicao;
    private javax.swing.JRadioButton rbPesquisarCotacao;
    private javax.swing.JRadioButton rbPesquisarPedidoCompra;
    private javax.swing.JRadioButton rbPesquisarRequisicaoCompra;
    private javax.swing.JRadioButton rbPesquisarSetor;
    private javax.swing.JRadioButton rbPesquisarTodas;
    private javax.swing.JTextField txtCotacao;
    private javax.swing.JTextField txtIdRequisicao;
    private javax.swing.JTextField txtPedidoDeCompra;
    // End of variables declaration//GEN-END:variables
}
